server:
  tomcat:
    max-threads: 1000
  port: 9000

---
management:
  server:
    address: 127.0.0.1
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  redis:
    database: 0
    password:
    port: 6379
    host: 127.0.0.1
    timeout: 1000
