server:
  tomcat:
    max-threads: 1000
  port: 9000

---
management:
  server:
    address: 127.0.0.1
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

---
bean:
  chance:
    id: 1
    name: n1

