server:
  tomcat:
    max-threads: 1000
  port: 9000

---
management:
  server:
    address: 127.0.0.1
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"

---
feign:
  client:
    url.ccb: https://api.virapi.com/vir_github256gbaa2a8b48/demo
    config:
      default:
        loggerLevel: FULL
        connectTimeout: 3300
        readTimeout: 4400

hystrix.plugin.HystrixConcurrencyStrategy.implementation : com.zxin.java.spring.feign.springmvc.HystrixConcurrencyStrategyMDC
