server:
  tomcat:
    max-threads: 1000
  port: 9000

---
management:
  server:
    address: 127.0.0.1
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"

---
nacos.config.server-addr: 127.0.0.1:8848
